services:
  celestia:
      image:  ghcr.io/celestiaorg/celestia-node:v0.21.9
      container_name: 'celestia'
      environment:
        - NODE_TYPE=light
        - P2P_NETWORK=mocha
        - RPC_URL=rpc-mocha.pops.one
        - RPC_PORT=9090
        - NETWORK=mocha
      command:
        - "celestia"
        - "light"  # node type: light, bridge, or full
        - "start"
        - "--core.ip"
        - "consensus-full-mocha-4.celestia-mocha.com"
        - "--core.port"
        - "9090"
        - "--p2p.network"
        - "mocha"
        - "--rpc.skip-auth"
        - "--rpc.addr"
        - "0.0.0.0"
      ports:
        - "2121:2121"
        - "26658:26658"
      volumes:
        - ${HOME}/.celestia-light-mocha-4:/home/celestia

  celestia-server-mocha:
      image: celestia-server:latest
      container_name: celestia-server
      environment:
      - CELESTIA_AUTH_TOKEN=${CELESTIA_AUTH_TOKEN:-}
      entrypoint: ["/bin/celestia-server", "--celestia.auth-token", \"$CELESTIA_AUTH_TOKEN\", "--celestia.namespace-id", "000008e5f679bf7116cb", "--celestia.rpc", "http://celestia:26658"]
      ports:
        - "1317:1317"
        - "9090:9090"
        - "26657:26657"
        - "1095:1095"
        - "8080:8080"
      depends_on:
        - celestia